# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Data And BI
tagline:          'Making sense of Data'
description:      'Blog related to the world of data and Business Intelligence revolving around it. Authored by <a href="https://ca.linkedin.com/in/nsharma7" target="_blank">Navneet</a>.'
url:              http://DataAndBI.com
baseurl:          /

author:
  name:           'Navneet Sharma'
  url:            https://ca.linkedin.com/in/nsharma7

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DataAndBI/DataAndBI.github.io

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
